server:
  port: 8081
---
spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: user-server
          uri: http://localhost:8082/
          predicates:
            - Path=/user/**
#          filters:
#            - name: UserFilter
#              args:
#                baseMessage: Spring Cloud Gateway UserFilter
#                preLogger: true
#                postLogger: true
        - id: post-server
          uri: http://localhost:8083/
          predicates:
            - Path=/post/**
#          filters:
#            - name: CafeFilter
#              args:
#                baseMessage: Spring Cloud Gateway CafeFilter
#                preLogger: true
#                postLogger: true